version: '3'
volumes:
  db:
  redis:
  app:
  file_uploads:
  derivatives:
  cache:
  branding:
  downloads:
  solr:
  data:

networks:
  internal:

services:

  solr:
    image: solr:9
    env_file:
      - .env
    environment:
      - OOM=script
      - SOLR_MODULES=analysis-extras,extraction
    command:
      - sh
      - -c
      - "precreate-core ${SOLR_TEST_CORE} /opt/solr/solr_conf && precreate-core ${SOLR_CORE} /opt/solr/solr_conf && exec solr -f --user-managed"
    networks:
      internal:
    expose:
      - 8983
    ports:
      - 8983:8983
    volumes:
      - solr:/var/solr
      - ./solr/conf:/opt/solr/solr_conf:rw
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8983/solr/"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      nofile:
        soft: 65000
        hard: 65000
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  appdb:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB_APP}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      internal:
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "POSTGRES_PASSWORD=${POSTGRES_PASSWORD} pg_isready -U ${POSTGRES_USER} -h localhost -d ${POSTGRES_DB_APP}"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  app: &app
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV}
        UPLOADS_PATH: ${UPLOADS_PATH}
        DERIVATIVES_PATH: ${DERIVATIVES_PATH}
        CACHE_PATH: ${CACHE_PATH}
        FITS_PATH: ${FITS_PATH}
        FITS_VERSION: ${FITS_VERSION}
        DOWNLOAD_PATH: ${DOWNLOAD_PATH}
        STORAGE_PATH: ${STORAGE_PATH}
    env_file:
      - .env
    networks:
      internal:

  web:
    <<: *app
    stdin_open: true
    tty: true 
    environment:
      - VIRTUAL_HOST=rdms.docker
      - VIRTUAL_PORT=3000
      - RAILS_FORCE_SSL=false
    command: bash -c "/bin/docker-entrypoint.sh"
    depends_on:
      - appdb
      - solr
      - redis
    networks:
      internal:
        aliases:
          - web
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - file_uploads:${UPLOADS_PATH}
      - derivatives:${DERIVATIVES_PATH}
      - cache:${CACHE_PATH}
      - downloads:${DOWNLOAD_PATH}
      - data:${STORAGE_PATH}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  workers:
    <<: *app
    stdin_open: true
    tty: true 
    command: bash -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    depends_on:
      - appdb
      - solr
      - redis
    volumes:
      - file_uploads:${UPLOADS_PATH}
      - derivatives:${DERIVATIVES_PATH}
      - cache:${CACHE_PATH}
      - downloads:${DOWNLOAD_PATH}
      - data:${STORAGE_PATH}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:8
    command: redis-server --appendonly yes
    networks:
      internal:
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - redis:/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

