development:
  host: <%= ENV['SOLR_HOST'] %>
  port: <%= ENV['SOLR_PORT'] %>
  core: <%= ENV['SOLR_CORE'] || 'hyrax_dev' %>
test:
  host: <%= ENV['SOLR_HOST'] %>
  port: <%= ENV['SOLR_TEST_PORT'] || '8985' %>
  core: <%= ENV['SOLR_TEST_CORE'] || 'hyrax_test' %>
production:
  host: <%= ENV['SOLR_HOST'] %>
  port: <%= ENV['SOLR_PORT'] %>
  core: <%= ENV['SOLR_CORE'] || 'hyrax_production' %>